const services = [

    {
        name: "Explore the Paris",
        key: 1,
        img_1: "https://i.ibb.co/wMtJnHc/paris-3-1.jpg",
        img_2: "https://i.ibb.co/K2rRd50/paris-2-1.jpg",
        img_3: "https://i.ibb.co/9vtYFWk/paris-1-1.jpg",
        duration: "Saturday to Tuesday ",
        include_1: "Food",
        include_2: "Accommodation",
        include_3: "Transport",
        dis: "Paris is one of the most attractive travel places in the world. If you are a traveler, why miss this opportunity. Fantasy Travels and Tourism provide you the opportunity to explore Paris. We offer food, accommodation, transportation and basic medical costs for this tour.",
        price: 5000,
        rating_Count: 540,
        rating: 4.5,
        rel_name: "Cindy Barsa",
        rel_img: "https://i.ibb.co/gjqSwyX/Client-2.jpg",
        rel_address: "Madrid, Spain",
        rel_text: "What a wonderful experience! The two tour leaders who were archaeologists enthralled us with the history of the Islands. The food was bountiful. On the boat the meals were wholesome and delicious. We were treated to wonderful meals on the the Islands that let us sample each Island's speciality. There was free time on each of the Islands that allowed for shopping, exploring or sitting round watching island life sipping a drink! The accommodation on the gulet was more than adequate with rooms being"
    },
    {
        name: "Discover the beauty of Sydney",
        key: 2,
        img_1: "https://i.ibb.co/vBHSg2h/sydney-1-1.jpg",
        img_2: "https://i.ibb.co/Q6WjPqj/sydney-3-1.jpg",
        img_3: "https://i.ibb.co/vk0xVyw/sydney-2-1.jpg",
        duration: "Friday to Tuesday ",
        include_1: "Food",
        include_2: "Accommodation",
        include_3: "Transport",
        dis: "Sydney is one of the most attractive travel places in the world. If you are a traveler, why miss this opportunity. Fantasy Travels and Tourism provide you the opportunity to explore Sydney. We offer food, accommodation, transportation and basic medical costs for this tour.",
        price: 4800,
        rating_Count: 482,
        rating: 5.00,
        rel_name: "Lura Page",
        rel_img: "https://i.ibb.co/vZ8F9dV/Client-1.jpg",
        rel_address: "Snjee, Singapur",
        rel_text: "What a wonderful experience! The two tour leaders who were archaeologists enthralled us with the history of the Islands. The food was bountiful. On the boat the meals were wholesome and delicious. We were treated to wonderful meals on the the Islands that let us sample each Island's speciality. There was free time on each of the Islands that allowed for shopping, exploring or sitting round watching island life sipping a drink! The accommodation on the gulet was more than adequate with rooms being"
    },
    {
        name: "The World Largest Sea Beach",
        key: 3,
        img_1: "https://i.ibb.co/7RMWk62/cox-Bazar-1.jpg",
        img_2: "https://i.ibb.co/pLxmJt7/cox-Bazar-2-1.jpg",
        img_3: "https://i.ibb.co/v4P4YTJ/cox-Bazar-3.jpg",
        duration: "Tuesday to Saturday",
        include_1: "Food",
        include_2: "Accommodation",
        include_3: "Transport",
        dis: "Cox’s Bazar is one of the most attractive travel places in the world. If you are a traveler, why miss this opportunity. Fantasy Travels and Tourism provide you the opportunity to explore Cox’s Bazar. We offer food, accommodation, transportation and basic medical costs for this tour.",
        price: 2800,
        rating_Count: 604,
        rating: 4.50,
        rel_name: "Mike Hanson",
        rel_img: "https://i.ibb.co/GxzX8m1/Client-4.jpg",
        rel_address: "Baising, China",
        rel_text: "What a wonderful experience! The two tour leaders who were archaeologists enthralled us with the history of the Islands. The food was bountiful. On the boat the meals were wholesome and delicious. We were treated to wonderful meals on the the Islands that let us sample each Island's speciality. There was free time on each of the Islands that allowed for shopping, exploring or sitting round watching island life sipping a drink! The accommodation on the gulet was more than adequate with rooms being"
    },
    {
        name: "Sylhet, the quine of nature",
        key: 4,
        img_1: "https://i.ibb.co/R7zZb2L/sylhet-2-1.jpg",
        img_2: "https://i.ibb.co/r5kk2ky/sylhet-3-1.jpg",
        img_3: "https://i.ibb.co/dts57yv/sylhet-1-1.jpg",
        duration: "Monday to Friday",
        include_1: "Food",
        include_2: "Accommodation",
        include_3: "Transport",
        dis: "Sylhet is one of the most attractive travel places in the world. If you are a traveler, why miss this opportunity. Fantasy Travels and Tourism provide you the opportunity to explore Sylhet. We offer food, accommodation, transportation and basic medical costs for this tour.",
        price: 3000,
        rating_Count: 861,
        rating: 5.00,
        rel_name: "Ela Brown",
        rel_img: "https://i.ibb.co/X2MzJRh/Client-3.jpg",
        rel_address: "London, UK",
        rel_text: "What a wonderful experience! The two tour leaders who were archaeologists enthralled us with the history of the Islands. The food was bountiful. On the boat the meals were wholesome and delicious. We were treated to wonderful meals on the the Islands that let us sample each Island's speciality. There was free time on each of the Islands that allowed for shopping, exploring or sitting round watching island life sipping a drink! The accommodation on the gulet was more than adequate with rooms being"
    },
    {
        name: "Explore Bangkok",
        key: 5,
        img_1: "https://i.ibb.co/bmGZHKV/thiland-1-1.jpg",
        img_2: "https://i.ibb.co/LnWXQ4P/thiland-2-1.jpg",
        img_3: "https://i.ibb.co/BfJhNsf/thiland-3-1.jpg",
        duration: "Friday to Saturday ",
        include_1: "Food",
        include_2: "Accommodation",
        include_3: "Transport",
        dis: "Bangkok is one of the most attractive travel places in the world. If you are a traveler, why miss this opportunity. Fantasy Travels and Tourism provide you the opportunity to explore Bangkok. We offer food, accommodation, transportation and basic medical costs for this tour.",
        price: 3500,
        rating_Count: 478,
        rating: 5.00,
        rel_name: "Heallry Jems",
        rel_img: "https://i.ibb.co/SxFKmyC/Client-5.jpg",
        rel_address: "Kolkata, India",
        rel_text: "What a wonderful experience! The two tour leaders who were archaeologists enthralled us with the history of the Islands. The food was bountiful. On the boat the meals were wholesome and delicious. We were treated to wonderful meals on the the Islands that let us sample each Island's speciality. There was free time on each of the Islands that allowed for shopping, exploring or sitting round watching island life sipping a drink! The accommodation on the gulet was more than adequate with rooms being"
    },
    {
        name: "Sundorbhan",
        key: 6,
        img_1: "https://i.ibb.co/VYRsJf7/sundorbhan-3-1.jpg",
        img_2: "https://i.ibb.co/dLbcLfy/sundorbhan-2-1.jpg",
        img_3: "https://i.ibb.co/C9VqYpf/sundorbhan-1-1.jpg",
        duration: "Saturday to Friday",
        include_1: "Food",
        include_2: "Accommodation",
        include_3: "Transport",
        dis: "Sundorbhan is one of the most attractive travel places in the world. If you are a traveler, why miss this opportunity. Fantasy Travels and Tourism provide you the opportunity to explore Sundorban. We offer food, accommodation, transportation and basic medical costs for this tour.",
        price: 2500,
        rating_Count: 481,
        rating: 4.50,
        rel_name: "Steve Huyen",
        rel_img: "https://i.ibb.co/p32qdxv/Client-6.jpg",
        rel_address: "New York, USA",
        rel_text: "What a wonderful experience! The two tour leaders who were archaeologists enthralled us with the history of the Islands. The food was bountiful. On the boat the meals were wholesome and delicious. We were treated to wonderful meals on the the Islands that let us sample each Island's speciality. There was free time on each of the Islands that allowed for shopping, exploring or sitting round watching island life sipping a drink! The accommodation on the gulet was more than adequate with rooms being"
    }
]